---
name: language-thrift
version: 0.12.0.1
license: BSD3
author: Abhinav Gupta
maintainer: Abhinav Gupta <mail@abhinavg.net>
github: abhinav/language-thrift
category: Language
synopsis: Parser and pretty printer for the Thrift IDL format.
description: |
    This package provides a parser and pretty printer for the
    <http://thrift.apache.org/docs/idl Thrift IDL format>.

extra-source-files:
  - CHANGES.md
  - examples/generateHaskellTypes.hs
  - examples/reformatIDL.hs
  - README.md
  - test/data/*.txt

ghc-options: -Wall

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.5 && < 0.7
  - megaparsec >= 9.0 && < 10.0
  - prettyprinter-compat-ansi-wl-pprint >= 1.0 && < 2.0
  - scientific >= 0.3 && < 0.4
  - semigroups >= 0.18 && < 0.21
  - text >= 1.2
  - transformers

library:
  source-dirs: src
  exposed-modules:
    - Language.Thrift.AST
    - Language.Thrift.Parser
    - Language.Thrift.Pretty

tests:
  spec:
    source-dirs: [src, test]
    main: Main.hs
    dependencies:
      - hspec >= 2.0
      - language-thrift
      - QuickCheck >= 2.5
    build-tools:
      - hspec-discover:hspec-discover >= 2.1
